site_name: The Illustrated GraphBLAS

nav:
  - Introduction: Chapter0.md
  - Python GraphBLAS: Chapter1.md
  - Semirings and Accumulation: Chapter2.md
  - Masking and BFS: Chapter3.md
  - Matrix-Matrix Multiplication: Chapter4.md
  - Incidence Matrices: Chapter5.md
  - Element-wise Operations and Transformations: Chapter6.md
  - Shortest Path: Chapter7.md
  - Triangle Counting and Centrality: Chapter8.md
  - Sparse Neural Networks: Chapter9.md
  
theme:
  name: material
  highlightjs: true
  hljs_languages:
    - C
    - python
    - pgsql
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences    

